# Generated by Django 3.1 on 2021-10-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
