# Generated by Django 3.1 on 2021-10-22 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20211021_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Mahsulot_nomi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoriya',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='malumot',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='narxi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='toyifa',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='yaratilgan_vaqt',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
