# Generated by Django 3.1 on 2021-10-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20211022_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Mahsulot_nomi',
            new_name='mahsulot_nomi',
        ),
    ]
