# Generated by Django 3.1 on 2021-10-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20211022_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoriya',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='yaratilgan_vaqt',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='malumot',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mahsulot_nomi',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='narxi',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='toyifa',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
